apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/feprevot/fprevot-iot-p3.git
    targetRevision: HEAD
    path: apps/playground
  syncPolicy:
    automated:
      selfHeal: true
      prune: true


