config_vars = Hash[File.readlines("confs/config.env").map { |line| line.strip.split('=', 2) }]

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder "./confs", "/vagrant"
  
  [
    ["#{config_vars['USER']}S", config_vars["CONTROLLER_IP"], 2048, 2, "controller", true],
    ["#{config_vars['USER']}SW", config_vars["WORKER_IP"], 1024, 1, "agent", false]
  ].each do |name, ip, memory, cpus, role, primary|
    config.vm.define name, primary: primary do |machine|
      machine.vm.hostname = name
      machine.vm.network "private_network", ip: ip
      machine.vm.provider("virtualbox") { |vb| vb.name = name; vb.memory = memory; vb.cpus = cpus }
      machine.vm.provision "shell", path: "scripts/setup.sh", args: [role]
    end
  end
end
