apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.gitlab.io/
    chart: gitlab
    targetRevision: 9.2.1
    helm:
      values: |
        upgradeCheck:
          enabled: false
        nginx-ingress:
          enabled: false
        certmanager:
          install: false
        certmanager-issuer:
          enabled: false
          email: qroyo.student@42lyon.fr
        prometheus:
          install: false
        gitlab-runner:
          install: false
        registry:
          enabled: false
        global:
          edition: ce
          hosts:
            domain: qroyo.com
            https: true
            externalIP: 127.0.0.1
            gitlab:
              name: gitlab.qroyo.com
              https: true
          kubernetes:
            inCluster: true
          grafana:
            enabled: false
          ingress:
            enabled: true
            class: "traefik"
          minio:
            enabled: false
          kas:
            enabled: false
          appConfig:
            artifacts:
              enabled: false
            lfs:
              enabled: false
            uploads:
              enabled: false
            packages:
              enabled: false
          gitaly:
            enabled: true
            persistence:
              size: 1Gi
          shell:
            port: 22
          migrationsTimeout: 1200
          time_zone: UTC
        gitlab:
          webservice:
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: "traefik"
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
              tls:
                enabled: true
                secretName: gitlab-tls-cert
              hosts:
                - host: gitlab.qroyo.com
                  paths:
                    - path: /
                      pathType: Prefix
              service:
                port: 8080
          sidekiq:
            minReplicas: 1
            maxReplicas: 1
            resources:
              requests:
                cpu: 100m
                memory: 800Mi
          gitlab-shell:
            enabled: false
          kas:
            enabled: false
          toolbox:
            enabled: false
          migrations:
            enabled: true
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
